### ISSUE TITLE
problem with Mullliken charges

### ISSUE THREAD

**Issue by maxivanoff** [orbkit/orbkit#1]
Hello,

Trying to educate myself on how to use orbkit, and got into a trouble of getting proper Mulliken charges in case of water when I use my fchk file. Provided h2o.molden file in the example folder works fine though, so not sure what I am doing wrong. See attached image and the com file I used for the calculation.
![image](https://cloud.githubusercontent.com/assets/5788334/22179164/175aba36-e011-11e6-9dac-576e42e99fa0.png)

%NProc=8
%Chk=water-N.chk
#P HF/6-31G(d)
opt
IOp(3/8=20)

 Title

0 1
@water-N.xyz

Would greatly appreciate any suggestions.

Thanks,
Max

**Comment by vpohl** [comment]
Dear Max,

thank you very much for pointing out this error. I have fixed it in my last commit. Now, everything works fine.

With best regards,
Vincent

**Comment by maxivanoff** [comment]
Hi Vincent,

Thanks for the response. 

I think something got messed up with how the number of atomic orbitals are counted. Please see my screenshot below.

![image](https://cloud.githubusercontent.com/assets/5788334/22215839/7121aed8-e162-11e6-9ff6-7e573ef884b9.png)

-Max

**Comment by vpohl** [comment]
Dear Max,
I see the problem. Your FChk file contains pure (not Cartesian) basis function and we have forgotten to implement this feature into the FChk reader. Sorry! I will do this tomorrow.

Thank you very much for pointing this out! 

Best regards,
Vincent

**Comment by maxivanoff** [comment]
Vincent,

In the calculation above, I've set IOp(3/8=20), which according to the gaussian manual forces 6D/10F (Cartesian).

However, when I set IOp(3/8=1), which forces 5D/7F, I get a different error. 

![image](https://cloud.githubusercontent.com/assets/5788334/22217580/252b98fc-e169-11e6-8bc4-ea34fea21d62.png)

-Max

**Comment by vpohl** [comment]
Dear Max,

thank you very much for pointing this out. The problem was still with the "SP" shells present in the Pople basis sets. Now, everything seems to work fine.

Best regards,
Vincent

**Comment by maxivanoff** [comment]
Thanks Vincent. Works perfectly now.
