### ISSUE TITLE
ordering of MOs

### ISSUE THREAD

**Issue by chstem** [orbkit/orbkit#18]
So far, MOs are automatically ordered by their energy eigenvalue when reading a QC output file. However, keeping the order of the file seems more intuitive and may be important for some use cases. For example natural UHF orbitals in a molden file may be ordered by occupation number.

I started to change this behavior to keep the original MO ordering from the file they are read from. Basically I removed `self.sort_by_energy()` from `update()` in `MOClass` (see [cfecd13](https://github.com/orbkit/orbkit/commit/cfecd1333792da557ffcf8f333f87c58e472ba71#diff-e45372c5a1e989d1719ce45f44f24071L603)). 
This causes some problem in the mo_select test, which still need to be addressed.

The `self.sort_by_energy()` was preceding a call to `self.get_spinstate()`. Was there any specific reason for that?

**Comment by lukasmarsoner** [comment]
To be honest - I don't remember ;)

This whole get_spinstate() thing is a hack and a bad one at that. As I already stated in my comment to the other issue I originally took the method from qcinfo because I was to lazy to implement a proper way of handling spins (particularly of getting them through all off the fancy selecting we are now doing in orbitals.py) so I thought just keeping the information in the labels and redetermining the associated arrays every time we create MOCall instances would work - I was wrong.

I think we should not keep fixing stupid decisions of the past. This method will only cause more problems in the future and the fix for it should be quite easy now that we have properly handled spin-index arrays.

@chstem would you be willing to apply the fix I laid out in my comment to the other issue?

**Comment by vpohl** [comment]
But was this really the issue? I thought the problem was that orbkit for some reason sorts the MOs by energy, what reduces the selection by index to absurdity. So on the one hand we want that the user selects the MOs by index in the output file and on the other hand we allow for keywords like homo, lumo, last_bound. Isn't this contradictory? 

By the way, you can reference to issues here: #17

**Comment by lukasmarsoner** [comment]
True - Thinking about the spinstate thing I completely forgot about the problem at hand, but Christian is clearly right: this should not be the default.

We can just leave it as a callable function as it might be quite useful.

**Comment by vpohl** [comment]
Yes, I completely agree, but what behavior does the user expect when he wants to compute, let's say, the homo and the lumo in the following three cases:

case 1a: 
1. MO (energy=-3) occ = 2
2. MO (energy=-2) occ = 0
3. MO (energy=-1) occ = 2
4. MO (energy= 0) occ = 0

case 1b: 
1. MO (energy=-3) occ = 2
2. MO (energy=-1) occ = 0
3. MO (energy=-2) occ = 2
4. MO (energy= 0) occ = 0

case 2: 
1. MO (energy=-3) occ = 2, spin=alpha
2. MO (energy=-2) occ = 2, spin=alpha
3. MO (energy=-1) occ = 0, spin=alpha
4. MO (energy= 0) occ = 0, spin=alpha
5. MO (energy=-3) occ = 2, spin=beta
6. MO (energy=-2) occ = 2, spin=beta
7. MO (energy=-1) occ = 0, spin=beta
8. MO (energy= 0) occ = 0, spin=beta

**Comment by lukasmarsoner** [comment]
Ahhh - yea! That was the reason the do the energy sorting in the first place... I think Turbomole always has them sorted, irrespective of the spin, right? Anyway: I would say that when not specifying a spin, the user would expect the function to return orbitals the "Turbomole way" i.w. just sorted by energy.

We could generate an array of sorted MO indices whenever the user uses sort() calles involving one of those fancy keywords "HOMO", "LUMO", LASTBOUND"... and then, without resorting the MO class itself, return the energy-sorted MOs?

**Comment by vpohl** [comment]
Okay, what should be the results for the three cases for '1,homo,lumo,homo-1'? 
1a) [2.MO, 3.MO,2.MO,2.MO]
1b) [2.MO, 3.MO,2.MO,1.MO]
2)   [2.MO,2.MO or 6.MO, 3.MO or 7.MO, 1.MO or 5.MO]

That is that we are sorting the MOs for the fancy keywords and not for homo, lumo, etc.? But what about natural orbitals, where the energy is not that well defined anymore?

**Comment by lukasmarsoner** [comment]
1. By "fancy" i really mean: "any keyword" i.e. also "homo", "lumo"... I say that, if one of them is contained within the string/list handed to sort() - we sort the MOs by energy. We can print out a warning to the user to make clear what we are doing. Also, this means that something like [1, homo, lumo] might not give the expected result but such is live.

2.  I'm not shure I see the problem: Is there even a reason to use homo, lumo... with NTOs? As you say their not eigenfunctions to the KS Hamiltonian so what would be the meaning of using a keyword like "homo" in that context?

**Comment by vpohl** [comment]
1. I can live with that, although it is a somehow unexpected behavior.
2. For natural orbitals it would be more natural to sort by occupation number. in this context homo would mean (as always) last occupied (up to a certain threshold) orbital.

**Comment by lukasmarsoner** [comment]
1. Yea - it's not great but I think it's the best of many bad options.
2. Other than geting the "HOMO" and "LUMO" can we really sort NTO's by occupation number? Won't it just be 2 or 0? I think we should think about selectively deactivating some of the keywors when one is dealing with special types of orbitals like NTO's. Also, given that they are not really MO's at all, we could also let the MOClass know what it is dealing with via a keyword which would then allow us to keep options from the user which might have unexpected results.

**Comment by chstem** [comment]
> We could generate an array of sorted MO indices whenever the user uses sort() calles involving one of those fancy keywords "HOMO", "LUMO", LASTBOUND"... and then, without resorting the MO class itself, return the energy-sorted MOs?

This seems reasonable and works intuitively, but only if you aware of the fact that the MOs may be ordered due to different criteria. A new user might not be aware, an experience might overlook it and get unexpected results. For example if the HOMO has index 3, then `'homo:homo+2'` will give a different set of orbitals than `'3:5'`.

When encountering one of the fancy keywords, one could first check if the MOs are ordered by energy. If not return an error message with a hint you need to call `sort_by_energy()` before. Hence the sorting will be done explicitly by the user and is thus obvious.

> [Explicit is better than implicit.](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python)

For the high-level interface one could add a `--sort_by_energy` option.

**Comment by vpohl** [comment]
For the high-level interface, I wouldn't introduce yet another keyword. We already have too many! There we do should it as we find it most intuitive. 

For the low-level you suggest that we beforehand check if the molecular orbitals are ordered by energy and then print a user warning that he might use `sort_by_energy()` beforehand? As the MOs are in 90% of the cases already sorted correctly, I would agree with doing that. @lukasmarsoner what do you think?

**Comment by chstem** [comment]
I was actually thinking about an error, not a warning. I don't think such an request would yield anything the user might expect, so we might just cancel this task at this point. Or is there a use case for having e.g. the  `homo` keyword for not energy sorted MOs?
