### ISSUE TITLE
calculating the MOs

### ISSUE THREAD

**Issue by lukhamm** [orbkit/orbkit#2]
Hi guys,
hope you are alright! 
Is there a way to tell orbkit.core that it should only calculate certain MOs? At the moment I have something like:
`orb = core.rho_compute(qc, calc_mo=True, slice_length=1e4, drv=None, numproc=1)`
which returns a numpy array with all MOs. Is it possible to get only certain MOs? I can't seem to get my head around it. (`read.mo_select` doesn't really work, since you have to pass the qc object as an element, right?).
Thanks.

**Comment by axelschild** [comment]
Hi Lukas,

yes, there is, and I guess the most instructive way to do this is given
in orbkit_low-level.py in the basic_examples directory.

There, the data of all MOs is loaded in the qc-object, and this is
transformed into a dictionary qc_select. From this dictionary, only the
selected orbital data (defined in selected_MO) is kept. Then qc_select
is used with rho_compute to get only the orbitals that you wanted.

Cheers

Axel

PS: In this example file, the <import orbkit as ok> statement calls
__init__.py from the orbkit directory which loads the function
rho_compute from module core into module ok.

**Comment by vpohl** [comment]
Hi Lukas,

Axel is right! You can select molecular orbitals as done in `orbkit_low-level.py`, but you can also use `read.mo_select` as you suggested. You only have to pass `qc.mo_spec` to this function, and afterwards overwrite `qc.mo_spec` by the return value. If you still need the old `qc` class instance, you can also prepare a copy of it::

`qc = read.main_read(fid,all_mo=True)`
`mo_info = mo_select(qc.mo_spec, 'HOMO:LUMO+4', strict=False)`
`qcnew = qc.copy()`
`qcnew.mo_spec = mo_info['mo_spec']`
`orb = core.rho_compute(qcnew, calc_mo=True, slice_length=1e4, drv=None, numproc=1)`

An even easier way to compute selected molecular orbitals is to use `extras.calc_mo`:

`qc = read.main_read(fid,all_mo=True)`
`orb,mo_info = extras.calc_mo(qc, 'HOMO:LUMO+4', slice_length=1e4, drv=None, numproc=1)`

With `otype=None` it does exactly the same as mentioned above.

Best regards,
Vincent

**Comment by lukhamm** [comment]
Hi again,
thanks for the quick response and the help! I just had time to implement it. So I tried the easy version with `extras.calc_mo` but in my case it seems to be slower than passing a new object with less orbitals (even slower than using all orbitals with the original qc). So I went with the first choices. It works fine now!
Thanks again.
Cheers,
Lukas
