### ISSUE TITLE
Question about orbkit vs. multiwfn for mulliken populations

### ISSUE THREAD

**Issue by adityanandy** [orbkit/orbkit#20]
Hello, I am attempting to use the orbkit package to obtain mulliken populations from a spin-unrestricted DFT calculation. I compared the mulliken charges obtained by orbkit to the mulliken charges obtained by multiwfn, but there are discrepancies in the mulliken charges for the same molden file. I was wondering if there is any reason as to why the two should be different. Thank you in advance for your assistance, and for the wonderfully documented package.

**Comment by vpohl** [comment]
Hi,
thank you very much for appreciating our program! We need some more details. Which QC program are you using? Is it possible to send us the molden file? Can you additionally provide us the Mulliken charges computed with multiwfn?

With best regards,
Vincent

**Comment by adityanandy** [comment]
Hi,
I figured out why there was a discrepancy. I was using terachem for my geometry optimizations, and the renormalization procedure in read.py (of the atomic orbitals in the molden file) in orbkit resulted in the difference. Commenting out this section gave me the same results as multiwfn. My apologies! Is there a reason that AO overlap is renormalized before calculating the mulliken populations? Thanks for your help and the quick reply!
Sincerely,
Aditya

**Comment by vpohl** [comment]
Hi,
I never used terachem but we implemented this renormalization procedure for orca. They somehow apply a different normalization constant for their atomic orbitals. This might be the same for terachem. Can you maybe check if your molecular orbitals are orthonormal with and without that renormalization of the atomic orbitals? That is for the cython (stable) branch

`from orbkit import analytical_integrals as ai`
...
`ao_overlap_matrix = ai.get_ao_overlap(qc.geo_spec,qc.geo_spec,qc.ao_spec,ao_spherical=qc.ao_spherical)`
`moom = ai.get_mo_overlap_matrix(qc.mo_spec,qc.mo_spec,ao_overlap_matrix)`
`assert numpy.allclose(moom, numpy.eye(len(moom)), tol=1e-5)`

(This code is adapted from our automatic testing procedure in our development branch)

**Comment by adityanandy** [comment]
Hi,
The assertion error is being raised for both with and without renormalization of the AOs. The sum of the squares of the MO coefficients in the molden file is less than one. I have attached the molden file I have been testing on as an example, as well as the values outputted by multiwfn. When I comment out the renormalization section, they match.

![screen shot 2018-06-21 at 4 06 20 pm](https://user-images.githubusercontent.com/7635801/41742792-10069ac8-756d-11e8-8627-fb11a2fe9da7.png)

[test.molden.zip](https://github.com/orbkit/orbkit/files/2125169/test.molden.zip)

**Comment by vpohl** [comment]
Hi,
you were absolutely right. The threshold in the if-clause `if sum(numpy.abs(norm-1.)) > 1e-8:` seems to be to tight. (TeraChem only prints 5 decimals in the molden file.) When I replace this statement by `if max(numpy.abs(norm-1.)) > 1e-5:` and when we then look on the MO overlap matrix considering only between the alpha or the beta orbitals, respectively, we get the expected diagonal matrix (with a deviation within the expected precision of the TeraChem molden file).

```
import numpy
from orbkit import read
from orbkit import analytical_integrals as ai
qc = read.main_read('test.molden',itype='molden',all_mo=True,spin='alpha')
ao_overlap_matrix = ai.get_ao_overlap(qc.geo_spec,qc.geo_spec,qc.ao_spec,ao_spherical=qc.ao_spherical)
moom = ai.get_mo_overlap_matrix(qc.mo_spec,qc.mo_spec,ao_overlap_matrix,numproc=4)

print(numpy.max(numpy.abs(moom - numpy.eye(len(moom)))))
assert numpy.allclose(moom, numpy.eye(len(moom)),atol=1e-4)
```

I will commit that change within the next days. Thank you again for pointing out this issue and of course for using orbkit!
