### ISSUE TITLE
Orbkit reads the incorrect number of MO coefficients

### ISSUE THREAD

**Issue by xxyxxyxyx1** [orbkit/orbkit#24]
I have read a molden.input file from a calculation using a basis of 36 contracted GTOs (def2-TZVP for a single calcium atom). Each MO in the molden file contains coefficients labeled 1 through 36. 

However, orbkit reads 39 coefficients for each MO, with the last three being zero. 

`
import orbkit as ok

ca0 = ok.read.main_read('ca0_xes.molden.input')

i = 0

len(ca0.mo_spec[i]['coeffs'])

39
`

This is true for any value of `i`. As long as the program is otherwise working properly, this just means I need to add a few `[:36]` to my script, but it was confusing / concerning. 

I have attached the molden file. It was generated from ORCA output using the `orca_2mkl` utility program that ships with ORCA. 
[ca0_xes.molden.input.txt](https://github.com/orbkit/orbkit/files/2972517/ca0_xes.molden.input.txt)

**Comment by vpohl** [comment]
Hi,
I will have a look into the problem within the next days.

**Comment by vpohl** [comment]
Hi,
thank you for reporting this bug. I could reproduce this behavior for the `cython` branch. Somehow orbkit does not recognize that the molden file contains spherical harmonic basis functions. I will fix this issue in that branch but for now you may switch to the [development branch](https://github.com/orbkit/orbkit/tree/development) which will very soon become the new _stable_ branch by checking out to that branch, rerunning the setup.py, and running the orbkit tests:
  ```
  git checkout development
  python setup.py build_ext --inplace clean
  orbkit test
  ```

Although we have rewritten most of the code base, there are only some minor changes for the user. If you have any questions, just contact us. So, concerning your input file. You can check the correctness by computing the MO overlap matrix and check if it is an identity matrix (with in your case 36 diagonal elements)

```
from orbkit import read
from orbkit.analytical_integrals import get_ao_overlap, get_mo_overlap_matrix, pmat

qc = read.main_read('ca0_xes.molden.input', all_mo=True)
aoom = get_ao_overlap(qc.geo_spec,qc.geo_spec,qc.ao_spec,drv=None)
moom = get_mo_overlap_matrix(qc.mo_spec,qc.mo_spec,aoom,numproc=4)
pmat(moom)
```

With best regards,
Vincent

**Comment by vpohl** [comment]
Fixed in `master` branch
