### ISSUE TITLE
atom_basis.update() error

### ISSUE THREAD

**Issue by jingjingshao0103** [orbkit/orbkit#31]
Dear all,

when I run my code, it appears following error. 

File "/home/jingjingshao/orbkit/orbkit/orbitals.py", line 203, in update
    self.update_ao_data()
  File "/home/jingjingshao/orbkit/orbkit/orbitals.py", line 236, in update_ao_data
    self._nprim_per_cont.append(len(cont_coeffs))
TypeError: len() of unsized object

where coeffs is one numpy.array()
I have already tried numpy.formstring() and list, both does not work. 
Any suggestion? 

Thank you!
Jingjing

**Comment by vpohl** [comment]
Hi Jingjing,
I hope you are doing well! What are you trying to do? I.e., how can I reproduce the error? It seems that there are not AO contraction coefficients.

**Comment by jingjingshao0103** [comment]
Hi Vincent,

thank you very much for the email. Actually it is this old code I am using
to read fitted the aos to the orbkit. Somehow with python3, it appears this
error.  I don't know whether you could reproduce this error...

path = '/home/jingjingshao/LINKER/Oktober/fitted_basis/'

for atom in numpy.unique(qc.geo_info[:,0]):

    with open(os.path.join(path,'{0}.dzp.basis.gto').format(atom)) as f:

        fitted_basis = json.load(f)

    atom_basis[atom] = AOClass()

    atom_basis[atom].spherical = True

    for bsf in fitted_basis:

        c = numpy.array(bsf['c']) / Bohr**1.5 # fitted basises are in
Angstrom....

        atom_basis[atom].append({'coeffs': numpy.array(zip(bsf['alpha'],c)),

                           'type': orbit[bsf['l']],

                           'lm': [(bsf['l'],m) for m in range(-bsf['l'],bsf[
'l']+1)],

                           'pnum': len(bsf['alpha']),

                           'atom': 0})

    atom_basis[atom].update()

Traceback (most recent call last):

  File "j.py", line 55, in <module>

    atom_basis[atom].update()

  File "/home/jingjingshao/orbkit/orbkit/orbitals.py", line 203, in update

    self.update_ao_data()

  File "/home/jingjingshao/orbkit/orbkit/orbitals.py", line 236, in
update_ao_data

    self._nprim_per_cont.append(len(cont_coeffs))

TypeError: len() of unsized object

Is this clear? Or how could I explain it better?

Stay WELL!
Jingjing

**Comment by jingjingshao0103** [comment]
Hi Vincent,

I know how to solve the problem now.
Just put 'coeffs': numpy.array(list(zip(bsf['alpha'],c)))

Cheers,
Jingjing
