### ISSUE TITLE
Cannot run sample on Mac: Line 146 in detci/ci_read.py 

### ISSUE THREAD

**Issue by HHChuang** [orbkit/orbkit#45]
Hi,

I am running sample testing on Mac, and file at file reading 

The error messages are: 

Opened 
        orbkit_test/lih_cis_aug-cc-pVTZ.out.default.molden

Loading molden file...

Content of the molden file:
        Found 3 [Molden Format] keywords, i.e., this file contains 3 molden files.
        Selecting the last element.
The atomic orbitals are not normalized correctly, renormalizing...

Opened 
        orbkit_test/lih_cis_aug-cc-pVTZ.out

Loading psi4_detci file...

Reading data of DETCI calculation from PSI4...
The input file orbkit_test/lih_cis_aug-cc-pVTZ.out contains
3 DETCI calculation(s) with 2, 1, and 1 root(s), respectively.
Traceback (most recent call last):
  File "/Users/Grace/Nextcloud/Work/Alex/run/../src/PTCDA_orbkit.py", line 90, in <module>
    qc, ci = detci.ci_read.main_ci_read(
  File "/Users/Grace/opt/orbkit/orbkit/detci/ci_read.py", line 68, in main_ci_read
    ci = reader[itype](filename,select_state=select,threshold=threshold, 
  File "/Users/Grace/opt/orbkit/orbkit/detci/ci_read.py", line 146, in psi4_detci
    raise IOError(str(i) + ' is not a valid selection for select_run')
OSError: 0 is not a valid selection for select_run

Some extra information about the version I've used: 

orbkit: 1.0 
macOS: 13.1
cython: 3.0.0b1 
numpy: 1.20.0 (since the developers use this version? ) 

I download test files and the release version of orbkit from this repo. After I fail to run test files, I tried to install everything by anaconda several times and switched versions of openmp, numpy and cython . 

If I use git in the terminal to download orbkit, the error message changes. 

Not sure which tests I can do, and any suggestions are helpful, thanks.

**Comment by vpohl** [comment]
@HHChuang, thank you for noticing this :)

Unfortunately we do not have mac machines and cannot reproduce the problem you describe.

Sorry we cannot be of more help

Cheers
Vincent
